# Generated by Django 4.1.5 on 2023-02-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='staticfiles/media/images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='thumb',
            field=models.ImageField(upload_to='staticfiles/media/thumbnails/'),
        ),
    ]
