# Generated by Django 4.1.5 on 2023-02-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_projects_image_alter_projects_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='build/static/media/images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='thumb',
            field=models.ImageField(upload_to='build/static/media/thumbnails'),
        ),
    ]
